"""
Reconciliation report — the "facilities moves / acquisition integration" muscle.

Takes the structured report produced by the ETL and renders RECONCILIATION.md:
what was auto-reconciled, what duplicates were resolved, and — most importantly —
an EXCEPTIONS QUEUE of rows that a human still has to make a call on (currency
conflicts, orphan records). Nothing is silently dropped; everything is accounted
for, which is exactly what you want when folding an acquired site into the portfolio.
"""
import os

from fip import db

REPORT_PATH = os.path.join(db.ROOT, "RECONCILIATION.md")


def write_report(conn, report, path=REPORT_PATH):
    acq = db.query(conn, "SELECT * FROM sites WHERE source_system = 'acquired_import'")
    lines = []
    a = lines.append

    a("# Acquisition Integration — Reconciliation Report\n")
    a("_Generated by `fip/reconcile.py`. Source: `seeds/acquired_site_dump.csv` "
      "and cross-system code drift in the HRIS/MRP/ERP exports._\n")

    a("## Summary\n")
    a(f"- **{len(report['actions'])}** records auto-reconciled into the canonical schema")
    a(f"- **{len(report['dedupes'])}** duplicate/conflicting row(s) resolved")
    a(f"- **{len(report['conflicts']) + len(report['exceptions'])}** item(s) in the "
      f"exceptions queue (need a human decision)")
    a(f"- Acquired site codes seen in the wild: "
      f"`{'`, `'.join(report['acquired_codes'])}` → all mapped to `quantico-acq`\n")

    a("## Canonical record produced\n")
    if acq:
        s = acq[0]
        a("| field | value |")
        a("|---|---|")
        for k in ("site_id", "site_name", "region", "sq_ft", "seat_capacity",
                  "site_type", "status", "source_system"):
            a(f"| {k} | {s[k]} |")
        a("")

    a("## Auto-reconciled\n")
    for act in report["actions"]:
        a(f"- {act}")
    a("")

    if report["dedupes"]:
        a("## Duplicate resolution\n")
        for d in report["dedupes"]:
            a(f"- {d}")
        a("")

    a("## ⚠️ Exceptions queue — needs human decision\n")
    if not (report["conflicts"] or report["exceptions"]):
        a("_None._\n")
    else:
        a("| # | source | issue | raw |")
        a("|---|---|---|---|")
        n = 0
        for c in report["conflicts"]:
            n += 1
            a(f"| {n} | acquired_site_dump.csv | currency/value conflict | {c} |")
        for e in report["exceptions"]:
            n += 1
            raw = str(e["row"]).replace("|", "\\|")
            a(f"| {n} | {e['source']} | {e['reason']} | `{raw}` |")
        a("")

    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path


def main():
    """Standalone: build a fresh DB, run the ETL, and write the report."""
    from fip import etl
    conn = db.connect()
    db.apply_schema(conn)
    report = etl.load_all(conn)
    db.apply_views(conn)
    conn.commit()
    path = write_report(conn, report)
    print(f"Reconciliation report written to {os.path.relpath(path)}")
    print(f"  • exceptions queue: {len(report['conflicts']) + len(report['exceptions'])} item(s)")
    conn.close()


if __name__ == "__main__":
    main()
